server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Sirve el build de React (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia backend-ventas
    location /api/ventas/ {
        proxy_pass http://backend-ventas/api/v1/ventas/;
    }

    # Proxy hacia backend-despacho
    location /api/despachos/ {
        proxy_pass http://backend-despacho/api/v1/despachos/;
    }
}