apiVersion: v1
kind: Service

metadata:
  name: backend-ventas

  # namespace del proyecto
  namespace: innovatech

spec:

  selector:
    app: backend-ventas

  ports:

  # puerto interno
  - port: 80

    # puerto contenedor
    targetPort: 8080

  type: ClusterIP