apiVersion: v1
kind: Secret

metadata:
  name: rds-secret
  namespace: innovatech

type: Opaque

stringData:

  DB_ENDPOINT: mysql-service
  DB_PORT: "3306"
  DB_NAME: innovatech
  DB_USERNAME: root
  DB_PASSWORD: root123